[package]
name = "nibleaf-biz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
nibleaf-db = { path = "../nibleaf-db" }
nibleaf-entity = { path = "../nibleaf-entity" }
nibleaf-error = { path = "../nibleaf-error" }
nibleaf-config = { path = "../nibleaf-config" }
nibleaf-auth = { path = "../nibleaf-auth" }
nibleaf-storage = { path = "../nibleaf-storage" }
nibleaf-search = { path = "../nibleaf-search" }
nibleaf-queue = { path = "../nibleaf-queue" }
nibleaf-access-control = { path = "../nibleaf-access-control" }
bytes = "1"

# Async
tokio = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
mockall = { workspace = true }

[lints]
workspace = true
