import { getLocale } from '../runtime.js';

const translations = {"ar":"ستحصل على صلاحيات مساحة عمل العميل. تجنب المحتوى الخاص إلا عند الحاجة لحل المشكلة، وأوقف الوصول عند الانتهاء.","bn":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","de":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","en":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","es":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","fr":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","hi":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","id":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","pt-BR":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","ru":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","ur":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished.","zh-CN":"You will have the customer’s workspace permissions. Avoid private content unless needed to resolve the reported issue, and stop access when finished."};

export function admin_support_cautionbody(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
