import { getLocale } from '../runtime.js';

const translations = {"ar":"لا يلزم. انشر الصفحات التي يحتاجها القارئ العربي أولًا، وحافظ على رابط واضح بين الصفحات المتقابلة فقط كي تعمل hreflang ومبدلات اللغة بصورة صحيحة.","bn":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","de":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","en":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","es":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","fr":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","hi":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","id":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","pt-BR":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","ru":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","ur":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly.","zh-CN":"No. Publish the pages Arabic readers need first and keep clear links between corresponding pages so hreflang and language switchers work correctly."};

export function blog_arabicchecklist_faqtreeanswer(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
