import { getLocale } from '../runtime.js';

const translations = {"ar":"أدلة وملاحظات من بناء Nibleaf حول بنية النشر وMarkdown والتوثيق ثنائي اللغة ومقارنات موثقة لأدوات التوثيق.","bn":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","de":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","en":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","es":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","fr":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","hi":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","id":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","pt-BR":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","ru":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","ur":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape.","zh-CN":"Guides and notes from building Nibleaf: deployment architecture, Markdown, bilingual documentation, and source-backed looks at the docs tooling landscape."};

export function blog_description(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
