import { getLocale } from '../runtime.js';

const translations = {"ar":"يدعم اتجاه RTL في القارئ والمحرر، وشجرة مستقلة لكل لغة، وعزل الشيفرة داخل النص، وبحثًا يستخدم tokenizer عربيًا مع تطبيع إملائي ومسار صرفي خفيف ومحافظ، إضافة إلى canonical وhreflang للصفحات المتقابلة.","bn":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","de":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","en":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","es":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","fr":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","hi":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","id":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","pt-BR":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","ru":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","ur":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages.","zh-CN":"Nibleaf supports RTL in the reader and editor, independent language trees, isolated inline code, Arabic-aware search, and canonical and hreflang metadata for corresponding pages."};

export function blog_arabicchecklist_faqsupportanswer(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
