import { getLocale } from '../runtime.js';

const translations = {"ar":"ابدأ بكلمات من صفحاتك نفسها، ثم جرّبها من دون تشكيل أو تطويل وبأشكال الألف المختلفة. اختبر الكلمات ذات البوادئ واللواحق أيضًا؛ يستخدم Nibleaf تطبيعًا إملائيًا ومسارًا صرفيًا خفيفًا ومحافظًا، مع إبقاء المطابقات الدقيقة في المرتبة الأعلى.","bn":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","de":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","en":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","es":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","fr":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","hi":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","id":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","pt-BR":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","ru":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","ur":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest.","zh-CN":"Start with words from your pages, then test them without diacritics or elongation and with different alef forms. Test common prefixes and suffixes while keeping exact matches ranked highest."};

export function blog_arabicchecklist_faqsearchanswer(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
