import { getLocale } from '../runtime.js';

const translations = {"ar":"لا. هذا يضبط اتجاه الصفحة، لكنه لا يعزل الأوامر والمسارات داخل الفقرات العربية، ولا يقلب الأيقونات الاتجاهية، ولا يجعل البحث واعيًا باختلاف كتابة الكلمات العربية.","bn":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","de":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","en":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","es":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","fr":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","hi":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","id":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","pt-BR":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","ru":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","ur":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants.","zh-CN":"No. It sets page direction but does not isolate commands and paths, flip directional icons, or make search understand Arabic spelling variants."};

export function blog_arabicchecklist_faqdirectionanswer(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
