import { getLocale } from '../runtime.js';

const translations = {"ar":"تظهر كتل MDX غير المدعومة ({tags}) للقراءة فقط مع الحفاظ على مصدرها. تبقى بقية الصفحة والتعليقات المرتبطة قابلة للتحرير.","bn":"অসমর্থিত MDX ব্লক ({tags}) শুধুমাত্র পঠনযোগ্য স্থানে রয়েছে এবং তাদের উৎস সংরক্ষিত আছে। পৃষ্ঠার বাকি অংশ এবং নোঙ্গর করা মন্তব্য সম্পাদনাযোগ্য থাকে।","de":"Nicht unterstützte MDX-Blöcke ({tags}) sind an Ort und Stelle schreibgeschützt und ihre Quelle bleibt erhalten. Der Rest der Seite und verankerte Kommentare bleiben bearbeitbar.","en":"Unsupported MDX blocks ({tags}) are read-only in place and their source is preserved. The rest of the page and anchored comments remain editable.","es":"Los bloques MDX ({tags}) no compatibles son de solo lectura y se conserva su origen. El resto de la página y los comentarios anclados siguen siendo editables.","fr":"Les blocs MDX non pris en charge ({tags}) sont en lecture seule et leur source est préservée. Le reste de la page et les commentaires ancrés restent modifiables.","hi":"असमर्थित MDX ब्लॉक ({tags}) केवल पढ़ने योग्य स्थान पर हैं और उनका स्रोत संरक्षित है। शेष पृष्ठ और एंकर टिप्पणियाँ संपादन योग्य रहेंगी।","id":"Blok MDX yang tidak didukung ({tags}) bersifat hanya baca dan sumbernya dipertahankan. Halaman lainnya dan komentar yang ditautkan tetap dapat diedit.","pt-BR":"Os blocos MDX ({tags}) não suportados são somente leitura e sua origem é preservada. O restante da página e os comentários ancorados permanecem editáveis.","ru":"Неподдерживаемые блоки MDX ({tags}) доступны только для чтения, и их источник сохраняется. Остальная часть страницы и закрепленные комментарии остаются редактируемыми.","ur":"غیر تعاون یافتہ MDX بلاکس ({tags}) صرف پڑھنے کی جگہ پر ہیں اور ان کا ماخذ محفوظ ہے۔ باقی صفحہ اور لنگر انداز تبصرے قابل تدوین رہیں گے۔","zh-CN":"不支持的 MDX 块 ({tags}) 是只读的，并且它们的源被保留。页面的其余部分和锚定评论仍然可编辑。"};

export function editor_unsupportedmdx_banner(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
