import { getLocale } from '../runtime.js';

const translations = {"ar":"يمكن تشغيل المنظومة كاملة من المصدر العام بترخيص AGPL-3.0، مع تحمّل المشغّل مسؤولية البنية وDNS وTLS والنسخ الاحتياطي والمراقبة والترقيات.","bn":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","de":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","en":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","es":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","fr":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","hi":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","id":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","pt-BR":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","ru":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","ur":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades.","zh-CN":"The complete platform can be self-hosted from the public AGPL-3.0 source; operators manage infrastructure, DNS, TLS, backups, monitoring, and upgrades."};

export function marketing_machine_arabic_selfhosting(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
