import { getLocale } from '../runtime.js';

const translations = {"ar":"اكتب وثائق المنتج بالعربية في محرر بصري فوق Markdown، مع بحث عربي ونشر متعدد اللغات واستضافة سحابية أو ذاتية.","bn":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","de":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","en":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","es":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","fr":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","hi":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","id":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","pt-BR":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","ru":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","ur":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment.","zh-CN":"Write Arabic product documentation in a visual Markdown editor with Arabic search, multilingual publishing, and cloud or self-hosted deployment."};

export function marketing_arabiclanding_description(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
