import { getLocale } from '../runtime.js';

const translations = {"ar":"يتضمن المصدر الرئيسي موارد وأدوات MCP مقيدة بالمشروع للمحتوى وتشخيص البحث والاستخدام والإضافات والتكاملات والعمليات والسمات. يمكن أن تنتهي المفاتيح المقيدة، ولا توجد عمليات كتابة.","bn":"Source main-এ content, search diagnostics, usage, add-ons, integrations, operations এবং themes-এর জন্য project-bound MCP resources ও tools রয়েছে। Scoped key-এর মেয়াদ শেষ হতে পারে; write operation উন্মুক্ত নয়।","de":"Source Main enthält projektgebundene MCP-Ressourcen und Werkzeuge für Inhalte, Suchdiagnosen, Nutzung, Add-ons, Integrationen, Vorgänge und Themes. Bereichsgebundene Schlüssel können ablaufen; Schreibvorgänge werden nicht bereitgestellt.","en":"Source main includes project-bound MCP resources and tools for content, search diagnostics, usage, add-ons, integrations, operations, and themes. Scoped keys can expire; write operations are not exposed.","es":"La rama principal del código fuente incluye recursos y herramientas MCP vinculados al proyecto para contenido, diagnósticos de búsqueda, uso, complementos, integraciones, operaciones y temas. Las claves con alcance pueden caducar; no se exponen operaciones de escritura.","fr":"La branche principale du code source comprend des ressources et outils MCP liés au projet pour le contenu, le diagnostic de recherche, l’usage, les modules complémentaires, les intégrations, les opérations et les thèmes. Les clés à portée limitée peuvent expirer ; aucune opération d’écriture n’est exposée.","hi":"Source main में content, search diagnostics, usage, add-ons, integrations, operations और themes के लिए project-bound MCP resources और tools शामिल हैं। Scoped keys की समय-सीमा समाप्त हो सकती है; write operations उपलब्ध नहीं हैं।","id":"Source main mencakup resource dan tool MCP yang terikat ke proyek untuk konten, diagnostik pencarian, penggunaan, add-on, integrasi, operasi, dan tema. Kunci dengan cakupan terbatas dapat kedaluwarsa; operasi tulis tidak disediakan.","pt-BR":"A branch principal do código-fonte inclui recursos e ferramentas MCP vinculados ao projeto para conteúdo, diagnóstico de pesquisa, uso, add-ons, integrações, operações e temas. Chaves com escopo podem expirar; operações de escrita não são expostas.","ru":"Основная ветка исходного кода содержит привязанные к проекту ресурсы и инструменты MCP для контента, диагностики поиска, использования, дополнений, интеграций, операций и тем. Срок действия ключей с ограниченной областью может истекать; операции записи не предоставляются.","ur":"Source main میں content، search diagnostics، usage، add-ons، integrations، operations اور themes کے لیے project-bound MCP resources اور tools شامل ہیں۔ Scoped keys کی میعاد ختم ہو سکتی ہے؛ write operations دستیاب نہیں ہیں۔","zh-CN":"源码主分支包含与项目绑定的 MCP 资源和工具，用于内容、搜索诊断、用量、附加功能、集成、操作和主题。限定范围的密钥可以过期；不提供写入操作。"};

export function marketing_release_mcpBody(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
