import { getLocale } from '../runtime.js';

const translations = {"ar":"عقد MCP في المصدر الرئيسي سطح منفصل ومقيد بالمشروع والصلاحيات وللقراءة فقط؛ وليس واجهة كتابة تستخدم جلسة لوحة التحكم.","bn":"Source main-এর MCP contract একটি পৃথক project-bound, scoped, read-only surface; এটি dashboard-session write API নয়।","de":"Der MCP-Vertrag in Source Main ist eine separate, projektgebundene, bereichsbegrenzte und schreibgeschützte Oberfläche; er ist keine Schreib-API für Dashboard-Sitzungen.","en":"The MCP contract in source main is a separate project-bound, scoped, read-only surface; it is not a dashboard-session write API.","es":"El contrato MCP de la rama principal del código fuente es una superficie independiente, vinculada al proyecto, con alcance limitado y de solo lectura; no es una API de escritura basada en la sesión del panel.","fr":"Le contrat MCP de la branche principale du code source est une surface distincte, liée au projet, à portée limitée et en lecture seule ; il ne s’agit pas d’une API d’écriture fondée sur la session du tableau de bord.","hi":"Source main का MCP contract एक अलग project-bound, scoped और read-only surface है; यह dashboard-session write API नहीं है।","id":"Kontrak MCP di source main adalah permukaan terpisah yang terikat ke proyek, memiliki cakupan terbatas, dan hanya-baca; kontrak ini bukan API tulis berbasis sesi dashboard.","pt-BR":"O contrato MCP na branch principal do código-fonte é uma superfície separada, vinculada ao projeto, com escopo limitado e somente leitura; não é uma API de escrita baseada na sessão do painel.","ru":"Контракт MCP в основной ветке исходного кода — это отдельная, привязанная к проекту, ограниченная по области и доступная только для чтения поверхность; это не API записи на основе сессии панели управления.","ur":"Source main کا MCP contract ایک الگ project-bound، scoped اور read-only surface ہے؛ یہ dashboard-session write API نہیں ہے۔","zh-CN":"源码主分支中的 MCP 合约是一个独立的、与项目绑定的、限定范围且只读的接口；它不是基于仪表板会话的写入 API。"};

export function marketing_release_mcpBoundary(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
