import { getLocale } from '../runtime.js';

const translations = {"ar":"اكتب وثائقك بصيغة ماركداون وانشر نسخة مؤرشفة. سيحصل القرّاء على موقع سريع وقابل للبحث بالخطوط التي تختارها هنا.","bn":"Markdown এ আপনার ডক্স লিখুন এবং একটি সংস্করণযুক্ত স্ন্যাপশট প্রকাশ করুন৷ পাঠকরা আপনার এখানে বেছে নেওয়া টাইপোগ্রাফি সহ একটি দ্রুত, অনুসন্ধানযোগ্য সাইট পান৷","de":"Schreiben Sie Ihre Dokumente in Markdown und veröffentlichen Sie einen versionierten Snapshot. Leser erhalten eine schnell durchsuchbare Website mit der hier ausgewählten Typografie.","en":"Write your docs in Markdown and publish a versioned snapshot. Readers get a fast, searchable site with the typography you choose here.","es":"Escriba sus documentos en Markdown y publique una instantánea versionada. Los lectores obtienen un sitio rápido y con capacidad de búsqueda con la tipografía que elija aquí.","fr":"Écrivez vos documents dans Markdown et publiez un instantané versionné. Les lecteurs bénéficient d'un site rapide et consultable avec la typographie que vous choisissez ici.","hi":"अपने दस्तावेज़ Markdown में लिखें और एक संस्करणित स्नैपशॉट प्रकाशित करें। पाठकों को यहां आपके द्वारा चुनी गई टाइपोग्राफी के साथ एक तेज़, खोजने योग्य साइट मिलती है।","id":"Tulis dokumen Anda di Markdown dan publikasikan snapshot berversi. Pembaca mendapatkan situs yang cepat dan mudah dicari dengan tipografi yang Anda pilih di sini.","pt-BR":"Escreva seus documentos em Markdown e publique um instantâneo com versão. Os leitores obtêm um site rápido e pesquisável com a tipografia que você escolher aqui.","ru":"Напишите свои документы в Markdown и опубликуйте версионный снимок. Читатели получают быстрый сайт с возможностью поиска и выбранной вами типографикой.","ur":"اپنے دستاویزات کو Markdown میں لکھیں اور ایک ورژن والا سنیپ شاٹ شائع کریں۔ قارئین کو آپ کی یہاں منتخب کردہ نوع ٹائپ کے ساتھ ایک تیز، قابل تلاش سائٹ ملتی ہے۔","zh-CN":"在 Markdown 中编写您的文档并发布版本化快照。读者可以使用您在此处选择的版式获得一个快速、可搜索的网站。"};

export function settings_typography_preview_body(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
