import { getLocale } from '../runtime.js';

const translations = {"ar":"اختر القرّاء الخاصين واحفظ وضع الوصول قبل إنشاء جماهير أو دعوات أو تسليم بوابة. تبقى سجلات القرّاء محفوظة عند تفعيل وضع آخر.","bn":"শ্রোতা, আমন্ত্রণ বা একটি পোর্টাল হ্যান্ডঅফ তৈরি করার আগে ব্যক্তিগত পাঠক চয়ন করুন এবং অ্যাক্সেস মোড সংরক্ষণ করুন৷ অন্য মোড সক্রিয় থাকলে বিদ্যমান পাঠক রেকর্ড সংরক্ষণ করা হয়।","de":"Wählen Sie „Private Leser“ und speichern Sie den Zugriffsmodus, bevor Sie Zielgruppen, Einladungen oder eine Portalübergabe erstellen. Bestehende Leserdatensätze bleiben gespeichert, wenn ein anderer Modus aktiv ist.","en":"Choose Private readers and save the access mode before creating audiences, invitations, or a portal handoff. Existing reader records remain stored when another mode is active.","es":"Elija Lectores privados y guarde el modo de acceso antes de crear audiencias, invitaciones o una transferencia del portal. Los registros del lector existentes permanecen almacenados cuando hay otro modo activo.","fr":"Choisissez Lecteurs privés et enregistrez le mode d'accès avant de créer des audiences, des invitations ou un transfert de portail. Les enregistrements de lecteur existants restent stockés lorsqu'un autre mode est actif.","hi":"निजी पाठक चुनें और ऑडियंस, आमंत्रण या पोर्टल हैंडऑफ़ बनाने से पहले एक्सेस मोड को सहेजें। कोई अन्य मोड सक्रिय होने पर मौजूदा रीडर रिकॉर्ड संग्रहीत रहते हैं।","id":"Pilih Pembaca pribadi dan simpan mode akses sebelum membuat audiens, undangan, atau penyerahan portal. Catatan pembaca yang ada tetap disimpan ketika mode lain aktif.","pt-BR":"Escolha Leitores privados e salve o modo de acesso antes de criar públicos, convites ou transferência de portal. Os registros do leitor existentes permanecem armazenados quando outro modo está ativo.","ru":"Выберите «Частные читатели» и сохраните режим доступа перед созданием аудиторий, приглашений или передачей портала. Существующие записи считывателей сохраняются, когда активен другой режим.","ur":"پرائیویٹ ریڈرز کا انتخاب کریں اور سامعین، دعوت نامے، یا پورٹل ہینڈ آف بنانے سے پہلے رسائی موڈ کو محفوظ کریں۔ جب کوئی دوسرا موڈ فعال ہوتا ہے تو موجودہ ریڈر ریکارڈز محفوظ رہتے ہیں۔","zh-CN":"在创建受众、邀请或门户移交之前，选择私人读者并保存访问模式。当另一种模式处于活动状态时，现有的读者记录仍会被存储。"};

export function settings_authentication_reader_inactivedescription(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
