import { getLocale } from '../runtime.js';

const translations = {"ar":"يؤدي تغيير بنية المستودع إلى إعادة ضبط ذاكرة الأساس المشترك وإنشاء أساس جديد بأمان. اترك بيانات الاعتماد فارغة للاحتفاظ بالرمز المشفّر.","bn":"রিপোজিটরি টপোলজি পরিবর্তন করা সাধারণ-বেস ক্যাশে পুনরায় সেট করে এবং নিরাপদে একটি নতুন বেসলাইন স্থাপন করে। এনক্রিপ্ট করা টোকেন রাখতে শংসাপত্রটি ফাঁকা রাখুন।","de":"Durch das Ändern der Repository-Topologie wird der Common-Base-Cache zurückgesetzt und sicher eine neue Baseline erstellt. Lassen Sie die Anmeldeinformationen leer, um das verschlüsselte Token zu behalten.","en":"Changing repository topology resets the common-base cache and safely establishes a new baseline. Leave the credential blank to keep the encrypted token.","es":"Cambiar la topología del repositorio restablece la caché de base común y establece de forma segura una nueva línea de base. Deje la credencial en blanco para conservar el token cifrado.","fr":"La modification de la topologie du référentiel réinitialise le cache de base commune et établit en toute sécurité une nouvelle référence. Laissez les informations d'identification vides pour conserver le jeton chiffré.","hi":"रिपॉजिटरी टोपोलॉजी बदलने से कॉमन-बेस कैश रीसेट हो जाता है और सुरक्षित रूप से एक नई बेसलाइन स्थापित हो जाती है। एन्क्रिप्टेड टोकन रखने के लिए क्रेडेंशियल को खाली छोड़ दें।","id":"Mengubah topologi repositori akan menyetel ulang cache basis umum dan menetapkan garis dasar baru dengan aman. Biarkan kredensial kosong untuk menyimpan token terenkripsi.","pt-BR":"A alteração da topologia do repositório redefine o cache de base comum e estabelece com segurança uma nova linha de base. Deixe a credencial em branco para manter o token criptografado.","ru":"Изменение топологии репозитория сбрасывает кэш общей базы и безопасно устанавливает новую базовую версию. Оставьте поле учетных данных пустым, чтобы сохранить зашифрованный токен.","ur":"ریپوزٹری ٹوپولوجی کو تبدیل کرنا کامن بیس کیشے کو دوبارہ سیٹ کرتا ہے اور محفوظ طریقے سے ایک نئی بیس لائن قائم کرتا ہے۔ خفیہ کردہ ٹوکن رکھنے کے لیے اسناد کو خالی چھوڑ دیں۔","zh-CN":"更改存储库拓扑会重置公共基础缓存并安全地建立新基线。将凭证留空以保留加密令牌。"};

export function settings_git_workflow_configurationdescription(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
