import { getLocale } from '../runtime.js';

const translations = {"ar":"لا تحتوي حقائق الفوترة إلا على المعرّفات المقيدة والطوابع الزمنية ومفاتيح المقاييس والكميات. لا تُخزن المطالبات أو الإجابات أو محتوى الوثائق أو المتجهات أو الأسرار أو عناوين IP أو وكلاء المستخدم الخام كحقائق استخدام.","bn":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","de":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","en":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","es":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","fr":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","hi":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","id":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","pt-BR":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","ru":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","ur":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts.","zh-CN":"Billing facts contain only scoped identifiers, timestamps, meter keys, and quantities. Prompts, answers, document content, vectors, secrets, IP addresses, and raw user agents are never stored as usage facts."};

export function settings_usage_privacyNote(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
