import { getLocale } from '../runtime.js';

const translations = {"ar":"أضِف push webhook في مضيف Git لديك يشير إلى رابط الاستلام. تُقبل توقيعات GitHub (X-Hub-Signature-256) ورموز GitLab السرية على حدّ سواء.","bn":"পেলোড ইউআরএলে নির্দেশ করে আপনার গিট হোস্টে একটি পুশ ওয়েবহুক যোগ করুন। GitHub-শৈলী স্বাক্ষর (X-Hub-Signature-256) এবং GitLab-শৈলী গোপন টোকেন উভয়ই গৃহীত হয়।","de":"Fügen Sie in Ihrem Git-Host einen Push-Webhook hinzu, der auf die Payload-URL verweist. Es werden sowohl Signaturen im GitHub-Stil (X-Hub-Signature-256) als auch geheime Token im GitLab-Stil akzeptiert.","en":"Add a push webhook in your Git host pointing at the payload URL. GitHub-style signatures (X-Hub-Signature-256) and GitLab-style secret tokens are both accepted.","es":"Agregue un webhook push en su host Git que apunte a la URL de carga útil. Se aceptan firmas de estilo GitHub (X-Hub-Signature-256) y tokens secretos de estilo GitLab.","fr":"Ajoutez un webhook push dans votre hôte Git pointant vers l'URL de la charge utile. Les signatures de style GitHub (X-Hub-Signature-256) et les jetons secrets de style GitLab sont tous deux acceptés.","hi":"अपने Git होस्ट में पेलोड URL की ओर इंगित करते हुए एक पुश वेबहुक जोड़ें। GitHub-शैली के हस्ताक्षर (X-Hub-Signature-256) और GitLab-शैली के गुप्त टोकन दोनों स्वीकार किए जाते हैं।","id":"Tambahkan webhook push di host Git Anda yang menunjuk ke URL payload. Tanda tangan bergaya GitHub (X-Hub-Signature-256) dan token rahasia bergaya GitLab keduanya diterima.","pt-BR":"Adicione um webhook push em seu host Git apontando para o URL da carga útil. Assinaturas estilo GitHub (X-Hub-Signature-256) e tokens secretos estilo GitLab são aceitos.","ru":"Добавьте на хост Git push-перехватчик, указывающий на URL-адрес полезной нагрузки. Принимаются как подписи в стиле GitHub (X-Hub-Signature-256), так и секретные токены в стиле GitLab.","ur":"پے لوڈ یو آر ایل کی طرف اشارہ کرتے ہوئے اپنے گٹ ہوسٹ میں پش ویب ہک شامل کریں۔ GitHub-سٹائل کے دستخط (X-Hub-Signature-256) اور GitLab-سٹائل کے خفیہ ٹوکن دونوں قبول کیے جاتے ہیں۔","zh-CN":"在 Git 主机中添加一个指向负载 URL 的推送 Webhook。 GitHub 样式签名 (X-Hub-Signature-256) 和 GitLab 样式秘密令牌均被接受。"};

export function settings_git_webhook_instructions_git(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
