import { getLocale } from '../runtime.js';

const translations = {"ar":"يعرض Mintlify التصدير كميزة مؤسسية. يُظهر Nibleaf السطح نفسه، لكن مهام PDF والتصدير الثابت غير مفعّلة بعد.","bn":"Mintlify একটি এন্টারপ্রাইজ বৈশিষ্ট্য হিসাবে রপ্তানি দেখায়। Nibleaf পৃষ্ঠকে দৃশ্যমান রাখে, কিন্তু PDF এবং স্ট্যাটিক রপ্তানি কাজগুলি এখনও সক্ষম করা হয়নি৷","de":"Mintlify zeigt Exporte als Enterprise-Funktion an. Nibleaf hält die Oberfläche sichtbar, aber PDF und statische Exportjobs sind noch nicht aktiviert.","en":"Mintlify shows exports as an Enterprise feature. Nibleaf keeps the surface visible, but PDF and static export jobs are not enabled yet.","es":"Mintlify muestra las exportaciones como una característica empresarial. Nibleaf mantiene la superficie visible, pero PDF y los trabajos de exportación estáticos aún no están habilitados.","fr":"Mintlify affiche les exportations en tant que fonctionnalité Entreprise. Nibleaf garde la surface visible, mais PDF et les tâches d'exportation statiques ne sont pas encore activées.","hi":"Mintlify निर्यात को एंटरप्राइज़ सुविधा के रूप में दिखाता है। Nibleaf सतह को दृश्यमान रखता है, लेकिन PDF और स्थैतिक निर्यात कार्य अभी तक सक्षम नहीं हैं।","id":"Mintlify menampilkan ekspor sebagai fitur Perusahaan. Nibleaf membuat permukaan tetap terlihat, namun PDF dan pekerjaan ekspor statis belum diaktifkan.","pt-BR":"Mintlify mostra as exportações como um recurso empresarial. Nibleaf mantém a superfície visível, mas PDF e trabalhos de exportação estáticos ainda não estão habilitados.","ru":"Mintlify показывает экспорт как функцию Enterprise. Nibleaf сохраняет поверхность видимой, но PDF и статические задания экспорта еще не включены.","ur":"Mintlify برآمدات کو ایک انٹرپرائز خصوصیت کے طور پر دکھاتا ہے۔ Nibleaf سطح کو مرئی رکھتا ہے، لیکن PDF اور سٹیٹک ایکسپورٹ جابز ابھی تک فعال نہیں ہیں۔","zh-CN":"Mintlify 将导出显示为企业功能。 Nibleaf 保持表面可见，但 PDF 和静态导出作业尚未启用。"};

export function settings_exports_enterprise_description(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
