import { getLocale } from '../runtime.js';

const translations = {"ar":"لا يخزن Nibleaf بيانات اعتماد API ولا يمرر طلبات التجربة عبر وسيط. يُدخل القراء البيانات داخل Scalar، ويجب أن يسمح خادم API بأصل الموقع عبر CORS.","bn":"Nibleaf সঞ্চয় করে না API শংসাপত্র বা প্রক্সি চেষ্টা করে দেখার অনুরোধ। পাঠকরা Scalar-এ শংসাপত্রগুলি প্রবেশ করান, এবং API সার্ভারকে অবশ্যই CORS দিয়ে তাদের সাইটের উত্সের অনুমতি দিতে হবে৷","de":"Nibleaf speichert keine API-Anmeldeinformationen oder Proxy-Try-it-Anfragen. Leser geben Anmeldeinformationen in Scalar ein und der API-Server muss ihren Site-Ursprung mit CORS zulassen.","en":"Nibleaf does not store API credentials or proxy try-it requests. Readers enter credentials in Scalar, and the API server must allow their site origin with CORS.","es":"Nibleaf no almacena las credenciales de API ni las solicitudes de prueba de proxy. Los lectores ingresan las credenciales en Scalar y el servidor API debe permitir el origen de su sitio con CORS.","fr":"Nibleaf ne stocke pas les informations d'identification API ni les demandes d'essai de proxy. Les lecteurs saisissent leurs informations d'identification dans Scalar et le serveur API doit autoriser l'origine de leur site avec CORS.","hi":"Nibleaf API क्रेडेंशियल या प्रॉक्सी प्रयास-अनुरोधों को संग्रहीत नहीं करता है। पाठक Scalar में क्रेडेंशियल दर्ज करते हैं, और API सर्वर को CORS के साथ अपनी साइट की उत्पत्ति की अनुमति देनी होगी।","id":"Nibleaf tidak menyimpan kredensial API atau permintaan percobaan proxy. Pembaca memasukkan kredensial di Scalar, dan server API harus mengizinkan situs asal mereka dengan CORS.","pt-BR":"Nibleaf não armazena credenciais API ou solicitações de teste de proxy. Os leitores inserem credenciais em Scalar, e o servidor API deve permitir a origem do site com CORS.","ru":"Nibleaf не хранит учетные данные API или запросы проверки прокси. Читатели вводят учетные данные в Scalar, а сервер API должен разрешить происхождение их сайта с помощью CORS.","ur":"Nibleaf API اسناد یا پراکسی آزمانے کی درخواستوں کو ذخیرہ نہیں کرتا ہے۔ قارئین Scalar میں اسناد داخل کرتے ہیں، اور API سرور کو اپنی سائٹ کی اصل CORS سے اجازت دینی چاہیے۔","zh-CN":"Nibleaf 不存储 API 凭据或代理尝试请求。读者在 Scalar 中输入凭据，并且 API 服务器必须允许其站点来源为 CORS。"};

export function settings_openapi_securityhint(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
