import { getLocale } from '../runtime.js';

const translations = {"ar":"استخدم رمز GitHub دقيق الصلاحيات مع قراءة Metadata وقراءة وكتابة Contents وPull requests. نتحقّق من هويتك الآن ولا نشفّر الرمز إلا بعد تأكيد الاتصال.","bn":"মেটাডেটা রিড, কন্টেন্ট রিড/রাইট এবং পুল রিকোয়েস্ট রিড/রাইট সহ একটি সূক্ষ্ম দানাদার GitHub টোকেন ব্যবহার করুন। আমরা এখন আপনার পরিচয় যাচাই করি এবং আপনি সংযোগ নিশ্চিত করার পরেই টোকেনটি এনক্রিপ্ট করি।","de":"Verwenden Sie ein feinkörniges GitHub-Token mit Lesen von Metadaten, Lesen/Schreiben von Inhalten und Lesen/Schreiben von Pull-Anfragen. Wir verifizieren jetzt Ihre Identität und verschlüsseln den Token erst, nachdem Sie die Verbindung bestätigt haben.","en":"Use a fine-grained GitHub token with Metadata read, Contents read/write, and Pull requests read/write. We verify your identity now and encrypt the token only after you confirm the connection.","es":"Utilice un token GitHub detallado con lectura de metadatos, lectura/escritura de contenidos y lectura/escritura de solicitudes de extracción. Verificamos su identidad ahora y ciframos el token solo después de que confirme la conexión.","fr":"Utilisez un jeton GitHub à granularité fine avec la lecture des métadonnées, la lecture/écriture du contenu et la lecture/écriture des requêtes Pull. Nous vérifions votre identité maintenant et chiffrons le jeton seulement après avoir confirmé la connexion.","hi":"मेटाडेटा पढ़ने, सामग्री पढ़ने/लिखने और पुल अनुरोधों को पढ़ने/लिखने के साथ बारीक GitHub टोकन का उपयोग करें। हम अब आपकी पहचान सत्यापित करते हैं और कनेक्शन की पुष्टि करने के बाद ही टोकन एन्क्रिप्ट करते हैं।","id":"Gunakan token GitHub yang terperinci dengan Metadata baca, Isi baca/tulis, dan permintaan Tarik baca/tulis. Kami memverifikasi identitas Anda sekarang dan mengenkripsi token hanya setelah Anda mengonfirmasi koneksi.","pt-BR":"Use um token GitHub refinado com leitura/gravação de metadados, leitura/gravação de conteúdo e leitura/gravação de solicitações pull. Verificamos sua identidade agora e criptografamos o token somente após você confirmar a conexão.","ru":"Используйте детализированный токен GitHub с чтением метаданных, чтением/записью содержимого и чтением/записью запросов на извлечение. Мы проверяем вашу личность сейчас и зашифровываем токен только после того, как вы подтвердите соединение.","ur":"میٹا ڈیٹا پڑھنے، مشمولات پڑھنے/لکھنے، اور پل کی درخواستوں کو پڑھنے/لکھنے کے ساتھ ایک عمدہ GitHub ٹوکن استعمال کریں۔ ہم ابھی آپ کی شناخت کی تصدیق کرتے ہیں اور کنکشن کی تصدیق کرنے کے بعد ہی ٹوکن کو انکرپٹ کرتے ہیں۔","zh-CN":"使用细粒度的 GitHub 令牌进行元数据读取、内容读/写和拉取请求读/写。我们现在验证您的身份，并仅在您确认连接后才对令牌进行加密。"};

export function settings_git_workflow_authorizedescription(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
