import { getLocale } from '../runtime.js';

const translations = {"ar":"GitHub: إعدادات المستودع ← Webhooks ← Add webhook — الصق رابط الاستلام والسر، واختر نوع المحتوى application/json، وحدد «Just the push event».","bn":"GitHub: রিপোজিটরি সেটিংস → ওয়েবহুক → ওয়েবহুক যোগ করুন — পেলোড URL এবং গোপনীয়তা পেস্ট করুন, অ্যাপ্লিকেশন/json-এ সামগ্রীর ধরন সেট করুন এবং \"শুধু পুশ ইভেন্ট\" নির্বাচন করুন৷","de":"GitHub: Repository-Einstellungen → Webhooks → Webhook hinzufügen – fügen Sie die Payload-URL und das Geheimnis ein, legen Sie den Inhaltstyp auf application/json fest und wählen Sie „Nur das Push-Ereignis“.","en":"GitHub: repository Settings → Webhooks → Add webhook — paste the payload URL and secret, set content type to application/json, and choose “Just the push event”.","es":"GitHub: Configuración del repositorio → Webhooks → Agregar webhook: pegue la URL de carga útil y el secreto, establezca el tipo de contenido en aplicación/json y elija \"Solo el evento push\".","fr":"GitHub : Paramètres du référentiel → Webhooks → Ajouter un webhook — collez l'URL de la charge utile et le secret, définissez le type de contenu sur application/json et choisissez « Juste l'événement push ».","hi":"GitHub: रिपॉजिटरी सेटिंग्स → वेबहुक → वेबहुक जोड़ें - पेलोड यूआरएल और सीक्रेट पेस्ट करें, सामग्री प्रकार को एप्लिकेशन/जेसन पर सेट करें, और \"जस्ट द पुश इवेंट\" चुनें।","id":"GitHub: Pengaturan repositori → Webhook → Tambahkan webhook — tempel URL payload dan rahasianya, atur jenis konten ke application/json, dan pilih “Just the push event”.","pt-BR":"GitHub: Configurações do repositório → Webhooks → Adicionar webhook — cole o URL e o segredo da carga útil, defina o tipo de conteúdo como application/json e escolha “Apenas o evento push”.","ru":"GitHub: Настройки репозитория → Веб-перехватчики → Добавить веб-перехватчик — вставьте URL-адрес полезной нагрузки и секретный код, установите тип контента application/json и выберите «Только событие push».","ur":"GitHub: ریپوزٹری سیٹنگز → ویب ہکس → ویب ہُک شامل کریں — پے لوڈ یو آر ایل اور سیکریٹ پیسٹ کریں، مواد کی قسم کو ایپلیکیشن/json پر سیٹ کریں، اور \"صرف دھکا ایونٹ\" کو منتخب کریں۔","zh-CN":"GitHub：存储库设置 → Webhooks → 添加 Webhook — 粘贴负载 URL 和密钥，将内容类型设置为 application/json，然后选择“仅推送事件”。"};

export function settings_git_webhook_instructions_github(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
