import { getLocale } from '../runtime.js';

const translations = {"ar":"حدّث مستنداتك تلقائيًا مع كل دفعة إلى فرع النشر. أضِف webhook إلى مستودعك — يتم التحقق من كل إرسال باستخدام السر أدناه.","bn":"ডিপ্লোয়মেন্ট ব্রাঞ্চে প্রতি ধাক্কায় আপনার ডক্স স্বয়ংক্রিয়ভাবে আপডেট করুন। আপনার সংগ্রহস্থলে একটি ওয়েবহুক যুক্ত করুন — বিতরণগুলি নীচের গোপনীয়তার সাথে যাচাই করা হয়৷","de":"Aktualisieren Sie Ihre Dokumente automatisch bei jedem Push an den Bereitstellungszweig. Fügen Sie Ihrem Repository einen Webhook hinzu – Lieferungen werden mit dem unten stehenden Geheimnis überprüft.","en":"Update your docs automatically on every push to the deployment branch. Add a webhook to your repository — deliveries are verified with the secret below.","es":"Actualice sus documentos automáticamente en cada envío a la rama de implementación. Agregue un webhook a su repositorio; las entregas se verifican con el secreto a continuación.","fr":"Mettez automatiquement à jour vos documents à chaque poussée vers la branche de déploiement. Ajoutez un webhook à votre référentiel : les livraisons sont vérifiées avec le secret ci-dessous.","hi":"परिनियोजन शाखा में प्रत्येक पुश पर अपने दस्तावेज़ों को स्वचालित रूप से अपडेट करें। अपने भंडार में एक वेबहुक जोड़ें - डिलीवरी नीचे दिए गए रहस्य से सत्यापित की जाती है।","id":"Perbarui dokumen Anda secara otomatis pada setiap dorongan ke cabang penerapan. Tambahkan webhook ke repositori Anda — pengiriman diverifikasi dengan rahasia di bawah ini.","pt-BR":"Atualize seus documentos automaticamente a cada envio para o branch de implantação. Adicione um webhook ao seu repositório — as entregas são verificadas com o segredo abaixo.","ru":"Обновляйте свои документы автоматически при каждом отправке в ветку развертывания. Добавьте вебхук в свой репозиторий — доставка проверяется с помощью секрета, приведенного ниже.","ur":"تعیناتی برانچ میں ہر دھکے پر اپنے دستاویزات کو خود بخود اپ ڈیٹ کریں۔ اپنے ذخیرے میں ایک ویب ہک شامل کریں — ڈیلیوری کی تصدیق نیچے دیے گئے راز سے ہوتی ہے۔","zh-CN":"每次推送到部署分支时都会自动更新您的文档。将 Webhook 添加到您的存储库 - 使用以下密钥验证交付。"};

export function settings_git_webhook_description(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
