import { getLocale } from '../runtime.js';

const translations = {"ar":"يجلب ملفات Markdown من مستودع GitHub أو GitLab أو Git عام عبر http(s) إلى صفحاتك. باتجاه واحد — لا تُدفع تعديلات Nibleaf إلى المستودع.","bn":"আপনার পৃষ্ঠাগুলিতে একটি সর্বজনীন GitHub, GitLab, অথবা http(গুলি) গিট রেপো থেকে Markdown ফাইলগুলিকে টেনে আনে৷ একমুখী — Nibleaf-এ সম্পাদনাগুলি পিছনে ঠেলে দেওয়া হয় না৷","de":"Zieht Markdown-Dateien aus einem öffentlichen GitHub-, GitLab- oder http(s)-Git-Repository in Ihre Seiten. Einseitig – Änderungen in Nibleaf werden nicht zurückgedrängt.","en":"Pulls Markdown files from a public GitHub, GitLab, or http(s) Git repo into your pages. One-way — edits in Nibleaf are not pushed back.","es":"Extrae archivos Markdown de un repositorio Git público GitHub, GitLab o http(s) en sus páginas. Unidireccional: las ediciones en Nibleaf no se retrasan.","fr":"Extrait les fichiers Markdown d'un référentiel Git public GitHub, GitLab ou http(s) dans vos pages. Unidirectionnel : les modifications dans Nibleaf ne sont pas repoussées.","hi":"सार्वजनिक GitHub, GitLab, या http(s) Git रेपो से Markdown फ़ाइलों को आपके पृष्ठों में खींचता है। एकतरफ़ा — Nibleaf में संपादन पीछे नहीं धकेले जाते।","id":"Menarik Markdown file dari GitHub, GitLab, atau http(s) repo Git publik ke halaman Anda. Satu arah — pengeditan di Nibleaf tidak ditunda.","pt-BR":"Extrai arquivos Markdown de um repositório público GitHub, GitLab ou http(s) Git para suas páginas. Unidirecional — as edições em Nibleaf não são adiadas.","ru":"Извлекает файлы Markdown из общедоступного репозитория GitHub, GitLab или http(s) Git на ваши страницы. В одну сторону — изменения в Nibleaf не отодвигаются.","ur":"آپ کے صفحات میں عوامی GitHub، GitLab، یا http(s) Git repo سے Markdown فائلوں کو کھینچتا ہے۔ یک طرفہ — Nibleaf میں ترامیم کو پیچھے نہیں دھکیلا جاتا ہے۔","zh-CN":"将 Markdown 文件从公共 GitHub、GitLab 或 http(s) Git 存储库提取到您的页面中。单向 — Nibleaf 中的编辑不会被推迟。"};

export function settings_git_onewaynote(params, options) {
  const locale = options?.locale || getLocale();
  const template = translations[locale] ?? translations["en"] ?? "";
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
}
