[package]
name = "nibleaf-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
async-trait = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
nibleaf-config = { path = "../nibleaf-config" }
nibleaf-db = { path = "../nibleaf-db" }
nibleaf-entity = { path = "../nibleaf-entity" }
nibleaf-error = { path = "../nibleaf-error" }

# Password hashing
argon2 = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
axum-extra = { version = "0.9", features = ["cookie"] }
tower = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
