[package]
name = "cms-biz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
cms-db = { path = "../cms-db" }
cms-entity = { path = "../cms-entity" }
cms-error = { path = "../cms-error" }
cms-config = { path = "../cms-config" }
cms-auth = { path = "../cms-auth" }
cms-storage = { path = "../cms-storage" }
cms-search = { path = "../cms-search" }
cms-queue = { path = "../cms-queue" }
cms-access-control = { path = "../cms-access-control" }
bytes = "1"

# Async
tokio = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
mockall = { workspace = true }

[lints]
workspace = true
