[package]
name = "nibleaf-access-control"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
nibleaf-entity = { path = "../nibleaf-entity" }
nibleaf-error = { path = "../nibleaf-error" }
nibleaf-db = { path = "../nibleaf-db" }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
